### PR TITLE
Remove Python 2.x special import logic

### PR DESCRIPTION
**Pull request by DanNixon**
Removes special import logic that was required for Python 2.x compatibility.

### CODE REVIEW

**Comment by martyngigg** [comment]
@DanNixon Is this still in progress?

**Comment by DanNixon** [comment]
For now, yes.

I was going to have a look though to see if there was version handling anywhere else in the codebase. These were just the ones I knew about/came to mind instantly.

**Comment by DanNixon** [comment]
I also wonder if it's worth removing the `future` imports yet?

I guess with them being at the top of files it makes it an easily revertable change if something came up and Python 2 was required again.

**Comment by martyngigg** [comment]
Yep, maybe leave them just for now.

**Comment by martyngigg** [comment]
Actually no I misunderstood your comment. Yes, let's remove them and they can be put back if necessary.

**Comment by DanNixon** [comment]
@martyngigg This is done now.

**Pull request merged**
