### PR TITLE
1610 disable enable spectrum export button

### PR DESCRIPTION
**Pull request by JackEAllen**
### Issue

Toggle state of spectrum viewer export button determined by stack being populated or not: #1610 

### Description

*Add a description of the changes made*.

The export button in the spectrum viewer was enabled when here was no active stack which caused a Value error if trying to export data. To resolve this:
* `set_export_button_enabled()` created in [view.py](https://github.dev/mantidproject/mantidimaging/blob/main/mantidimaging/gui/windows/spectrum_viewer/view.py) to toggle button enable state
* `handle_export_button_enabled()` created in [presenter.py](https://github.dev/mantidproject/mantidimaging/blob/main/mantidimaging/gui/windows/spectrum_viewer/presenter.py) to call `set_export_button_enabled()` with state when changes are made to stack in `handle_sample_change()`
* `can_export()` created in [model.py](https://github.dev/mantidproject/mantidimaging/blob/main/mantidimaging/gui/windows/spectrum_viewer/model.py) to return a boolean state based on whether there is an active stack loaded

### Testing 

*Describe the tests that were used to verify your changes*.

*  `test_WHEN_stack_value_set_THEN_can_export_returns_` created in [model_test.py](https://github.dev/mantidproject/mantidimaging/blob/main/mantidimaging/gui/windows/spectrum_viewer/test/model_test.py) which tests correct boolean state is returned by `can_export()` based on whether the stack is populated or None
* Tests checking stack changes (`test_handle_sample_change_no_new_stack()`,  `test_handle_sample_change_dataset_unchanged()`) in [presenter_test.py](https://github.dev/mantidproject/mantidimaging/blob/main/mantidimaging/gui/windows/spectrum_viewer/test/presenter_test.py) updated to include assertion to ensure that `set_export_button_enabled()` called with expected boolean argument if stack populated or not

### Acceptance Criteria 

*What is the acceptance criteria?*

- [ ] Export spectrum button is disabled if there not active stack in the spectrum viewer window.
- [ ] Export spectrum button enabled if there is an active stack in the spectrum viewer window.
- [ ] Export spectrum button when clicked does not trigger a ValueError when there is no active stack in the spectrum viewer window.

## How to Test

*verbose instructions for the reviewer to test changes*

- [ ] Open up GUI and Load Dataset `File > Load dataset > Sample`
- [ ] Open Spectrum Viewer `Workflow > Spectrum Viewer (Beta)
- [ ] Click the Export button and export a spectrum
- [ ] While keeping Spectrum Viewer window open, in the main window, delete the active stack by right clicking and selecting delete
- [ ] Go back to Spectrum Viewer window and validate export button is disabled
- [ ] While keeping Spectrum Viewer window open, in the main window, repeat steps one to three to validate that export button is enabled again and has expected behaviour.

### CODE REVIEW

**Review by rbauststfc — COMMENTED** [review]
These changes work really well and the code is nicely structured with good test coverage 👍
Just to check before approving, have we decided that a release note isn't needed for this change? I could see why we might not bother here, but I just wanted to double check.

**Comment by JackEAllen** [comment]
> These changes work really well and the code is nicely structured with good test coverage 👍 Just to check before approving, have we decided that a release note isn't needed for this change? I could see why we might not bother here, but I just wanted to double check.

I don't think we decided either way when discussing the issue originally. As this is technically fixing a bug, I think it would probably be good to include in release notes to formally say this has been fixed. Do you know where the release notes are for me to update?

**Comment by rbauststfc** [comment]
Great, that sounds good. The release notes are all stored under `docs/release_notes` in the repo. You'll want to add it to file `next.rst`, as these are the notes that we're building up for the next release. Just let me know if you have any other questions at all.

**Comment by JackEAllen** [comment]
Thank you! Will do that and let you know. 👍

**Review by rbauststfc — APPROVED** [review]

**Pull request merged**
