### PR TITLE
Add proper log level selection and tidy logging code

### PR DESCRIPTION
**Pull request by DanNixon**
- Replaces the `--verbosity` option with `--log-level` which accepts any of the standard Python log levels plus `TRACE`
- Adds the logger name to the output
- Removes special handing of `warnings`

To test:
- Run `mantidimaging-gui --log-level DEBUG` and compare it to `mantidimaging-gui --log-level INFO`

### CODE REVIEW

**Comment by DanNixon** [comment]
@DanNixon there are merge conflicts here, can you resolve them.

**Comment by martyngigg** [comment]
I seem to get the same output regardless of the log-level:

```sh
(py35) ✔  /media/data1/source/github/mantidproject/mantidimaging [pr/130-merged L|…10]
10:54 $ mantidimaging-gui --log-level DEBUG
2017-10-13 10:54:18,096 mantidimaging.helper DEBUG Logging initialised
2017-10-13 10:54:18,404 mantidimaging.core.configs.recon_config DEBUG CORs: None
2017-10-13 10:54:18,404 mantidimaging.core.configs.recon_config DEBUG COR slices: [0]
2017-10-13 10:54:18,532 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:122: UserWarning: Package mantidimaging.core.filters.crop$coords.crop_coords_gui._gui_register function not found!

2017-10-13 10:54:18,565 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:126: UserWarning: Package mantidimaging.core.filters.rebi$.rebin_gui_gui was not found! It is not registered with the GUI and it will not appear.

2017-10-13 10:54:18,582 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:126: UserWarning: Package mantidimaging.core.filters.wip.$cp_corrections.mcp_corrections_gui_gui was not found! It is not registered with the GUI and it will not appear.

2017-10-13 10:54:21,382 mantidimaging.gui.main_window.mw_view DEBUG Closing all PyPlot windows
(py35) ✔  /media/data1/source/github/mantidproject/mantidimaging [pr/130-merged L|…10] 
10:54 $ mantidimaging-gui --log-level INFO
2017-10-13 10:54:26,708 mantidimaging.helper DEBUG Logging initialised
2017-10-13 10:54:27,013 mantidimaging.core.configs.recon_config DEBUG CORs: None
2017-10-13 10:54:27,013 mantidimaging.core.configs.recon_config DEBUG COR slices: [0]
2017-10-13 10:54:27,135 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:122: UserWarning: Package mantidimaging.core.filters.crop$coords.crop_coords_gui._gui_register function not found!

2017-10-13 10:54:27,148 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:126: UserWarning: Package mantidimaging.core.filters.rebi$.rebin_gui_gui was not found! It is not registered with the GUI and it will not appear.

2017-10-13 10:54:27,160 py.warnings WARNING /media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/registrator/registrator.py:126: UserWarning: Package mantidimaging.core.filters.wip.$cp_corrections.mcp_corrections_gui_gui was not found! It is not registered with the GUI and it will not appear.
```

**Comment by DanNixon** [comment]
@martyngigg That looks like it's working to me. The two debug level messages from `recon_config` happen before the log level is actually set (during config validation). On the first log you see a debug level message that is not in the second (`Closing all PyPlot windows`).

**Comment by martyngigg** [comment]
Thanks, @DanNixon. I didn't spot that last line. Is it possible to configure the logging earlier so we don't get those messages out?

**Comment by DanNixon** [comment]
`56e0b69` moves log level setting to (close to) just after the argument parsing, there shouldn't be anything done between that would use logging.

Anything before argument parsing still goes out as debug, but there isn't really much done there either.

**Comment by martyngigg** [comment]
The only line left is `2017-10-13 13:56:09,013 mantidimaging.helper DEBUG Logging initialised`. Perhaps we could just move that outside of `intialize_logging()`

**Comment by DanNixon** [comment]
Removed that line it wasn't overly useful.

**Comment by martyngigg** [comment]
Agreed. :+1:

**Pull request merged**
