### PR TITLE
Fix creating sinograms

### LINKED ISSUE #1238: Unable to find stack for sinograms
### Summary
Clicking a sinogram stack in the dataset treeview gives an error.

Fix might be similar to #1221

### Steps To Reproduce

Open a dataset 
Image -> Create Sinograms from stack
Double click sinogram stack in sidebar

### Expected Behaviour

Focuses sinogram tab

### Current Behaviour
Error
`Unable to find stack with ID 3de1bf9e-1287-495f-a57f-c4229b336638`

### Context
Current main

### Failure Logs
```
2021-12-14 16:41:08,192 [mantidimaging.gui.windows.main.presenter:L69] ERROR: Notification handler failed
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/main/presenter.py", line 65, in notify
    self._focus_tab(**baggage)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/main/presenter.py", line 397, in _focus_tab
    raise RuntimeError(f"Unable to find stack with ID {stack_id}")
RuntimeError: Unable to find stack with ID 3de1bf9e-1287-495f-a57f-c4229b336638
```

### PR DESCRIPTION
**Pull request by samtygier-stfc**
### Issue

Closes #1238 

### Description

Missed from API changes, that prevent making sinograms at all.

Quick fix to put the sinograms in a StackDataset and adding it to the model.

A more complete fix should be done for #1273

### Testing & Acceptance Criteria 

Open a dataset
Image -> Create Sinograms from stack
Double click sinogram stack in sidebar

### Documentation

wait for the full fix

### CODE REVIEW

**Comment by rbauststfc** [comment]
The change seems to be working well for me and has certainly fixed the issue with sinograms not being created. I'm not sure if I'm doing the right thing to check the effect of double clicking the stack in the sidebar, though, as nothing appears to happen when I do that. I've been double clicking the stack names in the left hand bar of the main window, but should I be doing something else?

**Comment by samtygier-stfc** [comment]
Sorry, should have been clearer.
The newly created sinogram will be the visible tab already so double clicking its name in the side bar will do nothing. If you double click on one of the other stacks, its tab should come to the front, then double click on the sinogram to get it back.

**Comment by samtygier-stfc** [comment]
The test failure was the new TestGuiSystemLoading::test_save_images from  #1270.

I have set it to re run. I wonder if the timing in the test is unreliable :-(.

**Comment by rbauststfc** [comment]
> Sorry, should have been clearer. The newly created sinogram will be the visible tab already so double clicking its name in the side bar will do nothing. If you double click on one of the other stacks, its tab should come to the front, then double click on the sinogram to get it back.

Ah, thanks - I can get this effect if I create two sinogram stacks and then double clicking switches between them. Nothing switches for me if I have just one sinogram stack and then try to double click on the dataset I originally loaded, though. Does that sound right?

**Review by rbauststfc — APPROVED** [review]

**Pull request merged**
