### PR TITLE
Migrate 2.8 Release Notes

### PR DESCRIPTION
**Pull request by JackEAllen**
### Description

*Add a description of the changes made*.
* Migrate 2.8 release notes into `docs/release_notes/2.8.rst`
* Update `docs/release_notes/index.rst` to include version 2.8
* Clear `docs/release_notes/next`

### Testing 

*Describe the tests that were used to verify your changes*.
Self verified that Release notes documentation steps have been actioned

### Acceptance Criteria 

*How should the reviewer test your changes*?

Verify that release notes migration step has been completed correctly by checking against documented steps in internal developer docs.

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

NA

### CODE REVIEW

**Review by samtygier-stfc — CHANGES_REQUESTED** [review]
Can you add a `Mantid Imaging 2.8` title line to this like in `docs/release_notes/2.7.rst`

**Comment by JackEAllen** [comment]
> Can you add a `Mantid Imaging 2.8` title line to this like in `docs/release_notes/2.7.rst`

We should update docs to specific we should do this

**Review by samtygier-stfc — APPROVED** [review]
Looks good. I've tested building docs locally.

**Comment by samtygier-stfc** [comment]
I just want to understand why https://github.com/mantidproject/mantidimaging/actions/runs/9840498137/job/27164869490 failed before merging

**Comment by samtygier-stfc** [comment]
I think it is because we run `git rm -r -q -- ${dir_name}/[!0-9]*` to clear out things we don't need. But if there is nothing there then that command returns an error, so the action stops.

I'll make a quick PR for that.

**Comment by samtygier-stfc** [comment]
#2257

**Review by samtygier-stfc — APPROVED** [review]

**Comment by samtygier-stfc** [comment]
Built successfully https://mantidproject.github.io/mantidimaging/2.8.0/release_notes/2.8.html

**Pull request merged**
