### PR TITLE
Explicit tgv backend

### LINKED ISSUE #1985: Add TGV regularised LeastSquares reconstruction
### Desired Behaviour

To add the possibility to set up a Least Squares iterative reconstruction regularised with Total Generalised Variation, see https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193#d1e1364 section b.

### Current Behaviour

Only Total Variation regularisation is possible.

### PR DESCRIPTION
**Pull request by samtygier-stfc**
I made a branch of #1986 within the MI repo so that the PR can access the secrets on actions (I can't see a simple way to give the fork access).

### Issue

closes #1985 

### Description
Implementation of a Total Generalised Variation regulariser for Least Squares problems. It works both with PDHG and the SPDHG algorithms.

Controls to from the interface that are required:

1. `alpha`, regularisation parameter as in Eq. 3.5 https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193
2. `gamma`, ratio `beta/alpha`, wrt to Eq. 3.5 https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193
3. `regulariser`, whether `TV` or `TGV`

### Testing 

Edit `ReconstructWindowView.regulariser` to return `"TGV"`. In the reconstruction window select CIL:PDHG-TV, and check that it still does a reconstruction.

### Documentation

Wait for the GUI side

### CODE REVIEW

**Comment by MikeSullivan7** [comment]
Selecting CIL:PDHG-TV after changing the regulariser to TGV doesnt seem to produce a reconstruction preview, i.e.

image

and the reconstruction just gives a blank reconstruction.

I will do a deeper investigation to figure out what exactly is going on

**Comment by samtygier-stfc** [comment]
Do you get anything if you increase the number of iterations?

**Comment by MikeSullivan7** [comment]
After using `CIL: PDHG-TV` with "TGV" selected and toggling the "stochastic" option, I get an error: 


image

```
2024-04-25 09:42:30,166 [mantidimaging.gui.dialogs.async_task.task:L53] ERROR: Failed to execute task: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\gui\dialogs\async_task\task.py", line 50, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\core\utility\func_call.py", line 12, in call_with_known_parameters
    return func(**ka)
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\gui\windows\recon\model.py", line 132, in run_preview_recon
    recon.data[0] = reconstructor.single_sino(images.sino(slice_idx),
  File "C:\Users\ddb29996\mantidimaging\mantidimaging\core\reconstruct\cil_recon.py", line 249, in single_sino
    algo = SPDHG(f=F,
  File "C:\Users\ddb29996\AppData\Local\miniforge3\envs\mantidimaging-dev\lib\site-packages\cil\optimisation\algorithms\SPDHG.py", line 105, in __init__
    self.set_up(f=f, g=g, operator=operator, tau=tau, sigma=sigma,
  File "C:\Users\ddb29996\AppData\Local\miniforge3\envs\mantidimaging-dev\lib\site-packages\cil\optimisation\algorithms\SPDHG.py", line 156, in set_up
    norms = [operator.get_item(i,0).norm() for i in range(self.ndual_subsets)]
  File "C:\Users\ddb29996\AppData\Local\miniforge3\envs\mantidimaging-dev\lib\site-packages\cil\optimisation\algorithms\SPDHG.py", line 156, in <listcomp>
    norms = [operator.get_item(i,0).norm() for i in range(self.ndual_subsets)]
  File "C:\Users\ddb29996\AppData\Local\miniforge3\envs\mantidimaging-dev\lib\site-packages\cil\optimisation\operators\BlockOperator.py", line 136, in get_item
    return self.operators[index]
IndexError: tuple index out of range
2024-04-25 09:42:30,168 [mantidimaging.gui.mvp_base.view:L46] ERROR: show_error_dialog(): Encountered error while trying to reconstruct: tuple index out of range
```

Is this expected?

**Comment by samtygier-stfc** [comment]
Its expected not to work :-). The GUI (when it is done), will block setting stochastic for TGV. But we should probably have a better error message here.

**Review by MikeSullivan7 — APPROVED** [review]
Looks good, seems to match up with the paper and give good results with a higher number of iterations

**Pull request merged**
