### PR TITLE
Update python to 3.9

### LINKED ISSUE #1341: Investigate newer python version
### Desired Behaviour

Python 3.8 is no longer receiving bug fixes, so we need to move to 3.9 or 3.10.

A current constraint is CIL. It currently only supports up to 3.9 and only with numpy 1.20.

### PR DESCRIPTION
**Pull request by samtygier-stfc**
### Issue

Closes #1341

### Description

Update python to 3.9

No code changes needed

### Testing & Acceptance Criteria 
Tests should pass.

`python ./setup.py create_dev_env`

You might need to update the precommit hooks for the new python version:
`pre-commit install`

I have tested installing and running locally (linux) and IDAaaS.

### Documentation

Release notes

### CODE REVIEW

**Comment by rbauststfc** [comment]
Have you been able to create the environment on Windows? It failed for me with error:

`  - nothing provides openssl >=1.1.1m,<1.1.2a needed by python-3.9.10-h6cc024a_1`

I haven't had a look through to try and narrow down where the problem might be, but let me know if it would help for me to take a look.

Everything seems good on Linux, though.

**Comment by samtygier-stfc** [comment]
I'd not tested on windows. I'll see if I can work out the issue.

**Comment by samtygier-stfc** [comment]
The clash seems to be with astra-toolbox. On windows an environment with just `python=3.8.*` and `astra-toolbox=1.9.9` is fine. But with  `python=3.9.*` and `astra-toolbox=1.9.9` gives the openssl error.

 `python=3.9.*` and `astra-toolbox=2.0.0` also works.

We'll need to wait for a cil-astra which allows `astra-toolbox=2.0.0`

**Comment by samtygier-stfc** [comment]
CIL 21.4.0 and Astra 2.0 allow the all the conda packages to resolve on WIndows.

Next issue is installing pyqt with pip. Looks like it is attempting to build so missing a wheel?

**Comment by samtygier-stfc** [comment]
Updating the PyQt version fixes install but changes the spacing is several layouts. Looks like it is just removing unneeded white space, so an improvement.

image

**Comment by samtygier-stfc** [comment]
Splitting out the CIL and Qt parts into #1449 and #1452

**Comment by samtygier-stfc** [comment]
During testing I spotted some new warnings, but they are due to https://github.com/TomographicImaging/CIL/issues/1253 so don't need to block this PR.

**Review by rbauststfc — APPROVED** [review]

**Pull request merged**
