### PR TITLE
Adds Lock Histogram button and functionality

### LINKED ISSUE #705: Compare window - option to lock histograms to each other
This is done in the Refine window right now

### PR DESCRIPTION
**Pull request by dtasev**
- Refactors the common lock function into a base presenter mixin
- Adds tests

Not 100% sure about the choice of button here - currently it's a toggleable button, but maybe we should have a checkbox. This could be argued is more consistent with the Operations presenter, but that doesn't have an option to lock histogram ranges. I don't really mind either way.

To test:
- Load some data
- There's 2 ways to get to this dialog now:
	- Apply a filter with Safe Apply, try the Lock Histograms there
	- Go to Workflow > Compare, try the lock histograms there too

Fixes #705

### CODE REVIEW

**Comment by Pasarus** [comment]
I think we should use a check box, and would it be possible to lock the zoom levels of the histograms?

**Comment by Pasarus** [comment]
When you click lock histogram could it sync both of the histogram's data immediately? So for example say the ranges are mismatched when you toggle it on, then set them to the same value, with the left/original histogram being the "main" histogram that sets the range? maybe just the range that is largest.

**Comment by dtasev** [comment]
I think that should do it

**Review by Pasarus — APPROVED** [review]
Great new feature, great new tests :+1:

**Pull request merged**
