### PR TITLE
Add finer progress reporting to Tomopy recon

### LINKED ISSUE #197: Run TomoPy reconstruction manually
Allows finer grained progress reporting and cancellation.

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #197 

To test:
- Follow instructions from #192
- A progress dialog with a sensibly moving progress bar should appear
- OR, run `babylon5/DanNixon/test_recon.py`

### CODE REVIEW

**Comment by martyngigg** [comment]
@DanNixon I seem to get an exception raised during the reconstruction:

```
2017-11-29 14:25:50,406 [mantidimaging.core.utility.progress_reporting.progress] INFO: Elapsed time: 0 sec.
2017-11-29 14:28:11,391 [mantidimaging.core.utility.progress_reporting.progress] INFO: Elapsed time: 19 sec.
2017-11-29 14:29:43,251 [mantidimaging.core.utility.progress_reporting.progress] INFO: Elapsed time: 0 sec.
2017-11-29 14:29:43,251 [mantidimaging.gui.dialogs.async_task.task] ERROR: Failed to execute task
Traceback (most recent call last):
  File "/media/data1/source/github/mantidproject/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 46, in run
    self.task_function, *self.args, **self.kwargs)
  File "/media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/utility/func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
  File "/media/data1/source/github/mantidproject/mantidimaging/mantidimaging/gui/dialogs/tomopy_recon/model.py", line 64, in reconstruct_volume
    progress=progress)
  File "/media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/reconstruct/tomopy_reconstruction.py", line 67, in reconstruct
    algorithm='gridrec')
  File "/home/dmn58364/miniconda3/envs/py27/lib/python2.7/site-packages/tomopy/recon/algorithm.py", line 284, in recon
    tomo, center_arr, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
  File "/media/data1/source/github/mantidproject/mantidimaging/mantidimaging/core/reconstruct/tomopy_reconstruction.py", line 38, in monkey_patched_dist_recon
    ncore, slcs = tomopy.util.mproc.get_ncore_slices(
AttributeError: 'module' object has no attribute 'get_ncore_slices'
2017-11-29 14:29:43,317 [mantidimaging.gui.dialogs.tomopy_recon.presenter] ERROR: Reconstruction failed: 'module' object has no attribute 'get_ncore_slices'
```

**Comment by DanNixon** [comment]
Run `conda install -c conda-forge tomopy` and try again.

The newer versions of Tomopy are in the `conda-forge` channel it seems (it also seems I forgot to update the docs and build scripts to reflect this).

**Comment by martyngigg** [comment]
@DanNixon Thanks. That seems to be working now. There just seems to be a failing test on the CI server.

**Comment by DanNixon** [comment]
Yes, seems not all of the dependencies are pulled in correctly. I'm going to try the environment specification by a YAML file (instead of the hacky shell scripts currently used) and see if that helps.

**Comment by DanNixon** [comment]
@martyngigg For now I'm just installing the missing FFTW dependency manually in the build scripts.

I'm still going to go down the predefined environment route, but this is taking longer to get right then I expected.

**Comment by DanNixon** [comment]
Should be as long as reconstruction is still working for you locally.

**Comment by martyngigg** [comment]
I'll double check.

**Comment by DanNixon** [comment]
You will have to do `conda install -c dgursoy pyfftw` as well now.

**Pull request merged**
