### PR TITLE
Explicit TGV

### LINKED ISSUE #1985: Add TGV regularised LeastSquares reconstruction
### Desired Behaviour

To add the possibility to set up a Least Squares iterative reconstruction regularised with Total Generalised Variation, see https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193#d1e1364 section b.

### Current Behaviour

Only Total Variation regularisation is possible.

### PR DESCRIPTION
**Pull request by paskino**
### Issue

closes #1985 

### Description
Implementation of a Total Generalised Variation regulariser for Least Squares problems. It works both with PDHG and the SPDHG algorithms.

Controls to from the interface that are required:

1. `alpha`, regularisation parameter as in Eq. 3.5 https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193
2. `gamma`, ratio `beta/alpha`, wrt to Eq. 3.5 https://royalsocietypublishing.org/doi/10.1098/rsta.2020.0193
3. `regulariser`, whether `TV` or `TGV`

*Add a description of the changes made*.

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

### CODE REVIEW

**Comment by paskino** [comment]
I believe this code is ready to be tested by you @samtygier-stfc @JackEAllen

**Comment by samtygier-stfc** [comment]
@paskino Could you cherry-pick 746e96c55 faae8ebce and bbd84dd9a from https://github.com/mantidproject/mantidimaging/commits/paskino_explicit_TGV. That should get the tests passing. Thanks

**Comment by paskino** [comment]
@samtygier-stfc I need to think about how to make SPDHG work. Can it be disabled for now?

**Comment by samtygier-stfc** [comment]
Thanks. Ok. I'll merge as is, and will disable stochastic for TGV when I do the GUI.

Current test failures look like the applitools API is down, so I'll worry about that.

**Review by samtygier-stfc — APPROVED** [review]

**Comment by samtygier-stfc** [comment]
closing as we have #1997

**Review by MikeSullivan7 — COMMENTED** [review]
Looks good, seems to match up with the paper and give good results with a higher number of iterations

**Pull request closed without merging**
