### PR TITLE
Update Conda package script

### PR DESCRIPTION
**Pull request by DanNixon**
See commit messages for description.

To test:
- See that CI packaging passes
- Try to build the package locally and install it in a clean Conda environment (you will need the `conda-forge` and `dgursoy` channels added to your Conda config)
- Extract an archive from the [last PR job](http://builds.mantidproject.org/view/Imaging/job/mantidimaging-pull_requests/407/) and try installing the package locally

### CODE REVIEW

**Comment by martyngigg** [comment]
I was trying to install the archived copy and I must be doing something wrong. I create and activated a new python3.5 environment and then ran:

```
(imaging-test) ✔  /media/data1/source/github/mantidproject/mantidimaging [pr/267-merged L|…10] 
09:07 $ conda install --use-local --file ~/Downloads/mantidimaging_conda.tar.gz

`$ /home/dmn58364/miniconda3/bin/conda install --use-local --file /home/dmn58364/Downloads/mantidimaging_conda.tar.gz`

    Traceback (most recent call last):
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 683, in __call__
        return func(*args, **kwargs)
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 75, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 180, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "/home/dmn58364/miniconda3/lib/python3.6/site-packages/conda/cli/common.py", line 125, in specs_from_url
        for line in open(path):
      File "/home/dmn58364/miniconda3/lib/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte


     active environment : imaging-test
    active env location : /home/dmn58364/miniconda3/envs/imaging-test
            shell level : 1
       user config file : /home/dmn58364/.condarc
 populated config files : /home/dmn58364/.condarc
          conda version : 4.4.0rc2
    conda-build version : 2.1.17
         python version : 3.6.1.final.0
       base environment : /home/dmn58364/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/dgursoy/linux-64
                          https://conda.anaconda.org/dgursoy/noarch
                          https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/dmn58364/miniconda3/pkgs
                          /home/dmn58364/.conda/pkgs
       envs directories : /home/dmn58364/miniconda3/envs
                          /home/dmn58364/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.0rc2 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
Would you like conda to send this report to the core maintainers?
[y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

What am I doing wrong here?

**Comment by DanNixon** [comment]
@martyngigg Sorry, my instructions were not at all clear there.

To install it locally you unzip the archive and pass it as an additional channel to `conda install` (i.e. `conda install -c /path/to/mantidimaging_conda/`).

**Comment by martyngigg** [comment]
Thanks, @DanNixon. I was able to install the CI-built copy now.

I'm having trouble trying to build it locally though:

```
09:11 $ env PATH=$HOME/miniconda3/bin:$PATH conda-build --croot $PWD/mantidimaging_conda /media/data1/source/github/mantidproject/mantidimaging/conda/mantidimaging
BUILD START: mantidimaging-master-py35_0
    (actual version deferred until further download or env creation)
Solving environment: failed
Can't build /media/data1/source/github/mantidproject/mantidimaging/conda/mantidimaging due to unsatisfiable dependencies:

  - python==3.5
```

My base conda environment seems to be Python 3.6: could that cause an issue?

**Comment by DanNixon** [comment]
@martyngigg It shouldn't be an issue.

Can you post the output of `conda config --show`.

Also keep in mind the output directory cannot be on an encrypted file system (otherwise the filenames will be too long), not sure what your working directory was there so this may not be an issue.

**Comment by martyngigg** [comment]
@DanNixon No encryption here. My working directory:

```
✔  /media/data1/source/github/mantidproject/mantidimaging [pr/267-merged L|…16]
```

Output of `conda config --show`:

```
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - dgursoy
  - conda-canary
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  home/dmn58364/miniconda3/conda-bld: file:///
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: ["file:///home/dmn58364/miniconda3/conda-bld"]
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
download_only: False
envs_dirs:
  - /home/dmn58364/miniconda3/envs
  - /home/dmn58364/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
non_admin_enabled: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /home/dmn58364/miniconda3/pkgs
  - /home/dmn58364/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```

**Comment by DanNixon** [comment]
I'm not sure then. All I can see that is different is you having an additional channel (`file:///home/dmn58364/miniconda3/conda-bld`). But that should not stop finding packages in other channels...

**Comment by martyngigg** [comment]
Odd. It obviously builds on the CI server so I'll figure out my problem at some other point.

**Pull request merged**
