### PR TITLE
Remove "Specific Errors" and "Release Updates" from Table of Contents

### PR DESCRIPTION
**Pull request by ashmeigh**
### Issue

This pull request modifies the RST file to address the issue where "Specific Errors" and "Release Updates" were unintentionally displayed in the main table of contents. The proposed changes update these sections to use single underlines, ensuring consistency across the documentation.

Changes

Changed the underline style for "Specific Errors" and "Release Updates" from double underline to single underline.

### Acceptance Criteria 

These sections will not be featured in the main navigation panel. User's can still have access to these sections of the documentation.

### CODE REVIEW

**Comment by samtygier-stfc** [comment]
Can you try building this with `make build-docs` currently for me this removes the whole table of contents.

I think it will work to change the underline `=` to '-' for those sections that should not be top level.

**Comment by MikeSullivan7** [comment]
I can confirm that switching from `=` to `-` with a `maxdepth: 1` removes the Specific Errors and Release Updates from the list of contents: 

image


Also, for me the "Choose Version" dropdown in the top right doesn't seem to do anything, is this the same for other people?

**Comment by samtygier-stfc** [comment]
The version switcher needs a bit of effort to work on a local doc build (you need to have the old versions built in folders, and I think you need to actually serve it over http for the path to be right).

**Comment by MikeSullivan7** [comment]
Yeah Ive just check through the config file and thats the case, I dont have the past versions built locally.
Looks good to merge then if anybody else gets chance to have a look.

**Comment by ashmeigh** [comment]
Yeah, I've just checked through the config file, and that's the case. You need to have the past versions built locally and serve the documentation over HTTP for the version switcher to work correctly. Looks good to merge.

**Review by samtygier-stfc — APPROVED** [review]

**Pull request merged**
