### PR TITLE
Adds a check for available memory before allocating

### LINKED ISSUE #600: Try to prevent SIGBUS (Bus Error) when requesting too much memory
Currently Mantid Imaging will be terminated by the OS with SIGBUS if it tries to allocate memory over the maximum physically available.

We could _try_ to prevent this with a check in `create_shared_array` that calculates requested data size (`shape*dtype`) and compares it to available memory.

The helper functions for this should already be available, calculating data size is used in the load dialog, and I think available memory is sitting in a utility file, but not used anymore.

### PR DESCRIPTION
**Pull request by dtasev**
Adds a free memory getter in memory_usage package, and changes
get_memory_usage_linux to use psutil which should also make it run on Windows

### To test
- Try to load a dataset that's over your available RAM, or duplicate the data a bunch of times to reach that.
- Run Rebin or Crop on data where the temporary necessary for the operation cannot be allocated
  - Rebin to anything that's super big 
  - To get Crop to fail you can just crop by 99% of the image size, so as long you're somewhere above 50% memory usage

Fixes #600

### CODE REVIEW

**Review by Pasarus — CHANGES_REQUESTED** [review]
Largely looks good, can we add a way to ensure the progress window is closed/never opens? otherwise I get a fun little error:
image

**Comment by dtasev** [comment]
Which action caused this? Load, applying a filter, recon, etc - they all start and show the progress a bit differently so it'd be good to know to track it down

**Comment by Pasarus** [comment]
Loading

**Comment by dtasev** [comment]
I can't replicate this - I just get the error and no progress bar opens at all.

**Comment by dtasev** [comment]
Also I wonder if it might be better to check versus 95-97% of the actual available RAM - it seems a bit optimistic to expect to be 100% accurate, and I'd rather warn preemptively than get SIGBUSsed

**Comment by Pasarus** [comment]
That sounds like a good solution, because I managed to load all but 5 images of a 500ish stack so that inaccuracy is likely.

**Review by Pasarus — APPROVED** [review]

**Pull request merged**
