### PR TITLE
Filter GUIs - part 1

### PR DESCRIPTION
**Pull request by DanNixon**
Re #107 

Requires ~~#111~~ to be merged first.

- Adds a simple way of adding fields to a filter dialog
- Add GUIs for the following filters:
    - Cut off
    - Minus log
    - Rotate stack
    - Stripe removal
- Ensures that filter dialogs are created the correct size for the widgets they contain

To test:
  - Load a sample image (see `demoimages`)
  - Run some filters on it (all except stripe removal are pretty trivial)

### CODE REVIEW

**Comment by martyngigg** [comment]
@DanNixon We've got some merge conflicts here.

**Comment by DanNixon** [comment]
@martyngigg I should have added a note mentioning this needs #111 to be merged first.

**Comment by martyngigg** [comment]
@DanNixon I've merged #111 so we should be able to resolve these now.

**Comment by martyngigg** [comment]
@DanNixon Is there any documentation anywhere about what each of the filters is supposed to do?

**Comment by DanNixon** [comment]
Not at the moment.

Most of them are filters/operations the scientists are familiar with therefore the priority at the moment is making them work on the GUI (or at least be in a position for them to say they do not).

Documentation will be fully updated in time for it to be provided to users.

**Comment by martyngigg** [comment]
@DanNixon Ok. I think we should try and do this sooner rather than later. From a reviewers point of view at this level we may want to check that the intention of a filter matches with the implementation.

**Comment by martyngigg** [comment]
I was running the stripe removal filter with the default parameters and the log prints
```
Received parameter value ()
```
Is that an error or should the line be left out?

**Comment by DanNixon** [comment]
@martyngigg That log message is fine, it is just informing that the slice visualiser provided no parameters to the algorithm (filter) dialog. Really it should probably be debug level.

Re documentation, I've made a start on this now.

**Comment by martyngigg** [comment]
@DanNixon Thanks. We've got more merge conflicts to deal with but then this is good to go.

**Comment by martyngigg** [comment]
Some merge conflicts again, @DanNixon. Let me know when they're fixed and I'll get this one through.

**Comment by DanNixon** [comment]
@martyngigg Done

**Pull request merged**
